name: Idata Bot Runner

on:
  schedule:
    - cron: "*/10 * * * *"   # Her 10 dakikada bir çalışır
  workflow_dispatch:          # Manuel çalıştırma

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python idata_notify_playwright.py

