name: Run iData Bot

# Manuel veya zamanlı tetikleme
on:
  schedule:
    - cron: '*/5 * * * *'   # her 5 dakikada bir
  workflow_dispatch:        # manuel tetikleme

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    # 1. Repo'yu checkout et
    - uses: actions/checkout@v3

    # 2. Python kurulumu
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3. Kütüphaneleri yükle
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 playwright

    # 4. Playwright tarayıcılarını yükle
    - name: Install Playwright browsers
      run: playwright install

    # 5. Botu çalıştır
    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python idata_notify_playwright.py
