name: Run iData Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # her 5 dakikada bir
  workflow_dispatch:        # manuel tetikleme

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 playwright

    - name: Install Playwright browsers
      run: playwright install

    - name: Run bot
      run: |
        python idata_notify_playwright.py
